### ISSUE TITLE
(Win64) Incompatible type for argument 3 of 'sfRenderTexture_createWithSettings'

### ISSUE THREAD

**Issue by brus-fabrika** [Telroshan/go-sfml#8]
When building basic_window example (Win10 64bit) there is a compilation error:

```
Graphics_wrap.c: In function '_wrap_sfRenderTexture_createWithSettings_graphics_0e245b41439e98a6':
Graphics_wrap.c:4902:76: error: incompatible type for argument 3 of 'sfRenderTexture_createWithSettings'
 4902 |   result = (sfRenderTexture *)sfRenderTexture_createWithSettings(arg1,arg2,(sfContextSettings const *)arg3);
      |                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            const sfContextSettings *
In file included from d:\development\libs\CSFML\include/SFML/Graphics.h:45:
d:\development\libs\CSFML\include/SFML/Graphics/RenderTexture.h:68:131: note: expected 'sfContextSettings' but argument is of type 'const sfContextSettings *'
   68 | CSFML_GRAPHICS_API sfRenderTexture* sfRenderTexture_createWithSettings(unsigned int width, unsigned int height, sfContextSettings settings);
      |
~~~~~~~~~~~~~~~~~~^~~~~~~~
```

sfRenderTexture_createWithSettings in CSFML RenderTexture.h is indeed declared as accepting value object sfContextSettings, not the const pointer.

**Comment by brus-fabrika** [comment]
Update to the above - after manual update of the Graphics_wrap.c to pass the correct argument to underlying function sfRenderTexture_createWithSettings, I've got the linker errors:
```
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
D:/development/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\brusa\AppData\Local\Temp\go-link-4052965474\000002.o:Graphics_wrap.:(.text+0x624a): undefined reference to `__imp_sfRenderTexture_createWithSettings'
D:/development/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\brusa\AppData\Local\Temp\go-link-4052965474\000002.o:Graphics_wrap.:(.text+0x6b41): undefined reference to `sfRenderTexture_getMaximumAntialiasingLevel'
D:/development/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\brusa\AppData\Local\Temp\go-link-4052965474\000002.o:Graphics_wrap.:(.text+0xbeef): undefined reference to `__imp_sfTexture_updateFromTexture'
collect2.exe: error: ld returned 1 exit status
```

I do believe this is neither the compiler nor the CSFML lib versions issues, because I was able to build and run corresponding C version of the basic example correctly.

**Comment by Telroshan** [comment]
Hey!
Just ran a fresh install as I had formatted my computer since then, and it worked just fine for me 😕 
Could you tell me what your setup is? With versions and so on, so I can investigate, hopefully recreating the same bug in the same conditions!

I personnally ran :
- [CSFML 2.5.1 64 bits](https://www.sfml-dev.org/download/csfml/)
- [GCC x86_64-13.2.0-release-win32-seh-ucrt-rt_v11-rev0](https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-win32-seh-ucrt-rt_v11-rev0.7z)
- Ran the `build.bat` script in the example's folder, after adjusting the `CSFML_PATH` and adding gcc to my system Path

If you don't run the bat script, please make sure :
- You have properly set `CGO_ENABLED`, `CGO_CFLAGS` and `CGO_LDFLAGS` environment variables
- You have copied the CSFML 64 bits DLL next to your exe

**Comment by brus-fabrika** [comment]
@Telroshan hello!

After your comment I decided to make a fresh re-install of the building setup from the beginning and it just went fully fine at the end :) . My mistake was in CSFML version mismatch, somehow first time I downloaded 2.5 version, not the 2.5.1. With the latter it compiles and builds with no errors (except of deprecation warnings).

I will close the issue.

Thank you!

**Comment by Telroshan** [comment]
Perfect, I'm glad it's working, thanks for letting me know!
